-- ---------------------------------------------------------------------------
-- 01_schema.sql — physical landing schema for the NHTSA ODI flat files.
--
-- WHERE THIS FITS IN THE DEMO
-- ---------------------------
-- This file is the *antagonist* of the demo. It deliberately reproduces the
-- publisher's physical column names exactly as they appear in the flat file,
-- lowercased and nothing else:
--
--     cmplid  odino  compdesc  cmpl_type  ldate  datea  faildate
--     orig_equip_yn  loc_of_tire  occurences  prod_type  mfr_name
--
-- Three different date columns. A misspelled column (`occurences`, one 'r').
-- A misspelled column in recalls (`conequence_defect`, missing the 's').
-- No foreign keys, no friendly aliases, no documentation in the object names.
-- This is what an SAP-derived enterprise warehouse actually looks like, and it
-- is why an unaided frontier model gets Text-to-SQL wrong here.
--
-- DO NOT "clean this up". The cryptic names are the demo.
--
-- Everything is TEXT. That is deliberate, not laziness:
--   * The source is dirty (empty strings, literal spaces, 9999 for unknown year,
--     zero-filled numerics, dates that are not dates).
--   * A cast failure mid-COPY on stage is unrecoverable. Landing as TEXT means
--     the load cannot fail on data quality.
--   * The typed/derived layer is shown as a COMMENTED-OUT pattern at the bottom.
--     We do not create it, because a friendly typed view would hand the model the
--     answer and destroy the point of the demo.
--
-- RUN ORDER
-- ---------
--   1. sql/01_schema.sql          <-- you are here (run BEFORE loading)
--   2. data/load_nhtsa.py         COPY the flat files in
--   3. sql/02_comments.sql        GENERATED by scripts/generate_comments.py
--   4. sql/03_semantic_kb.sql     ...
--
-- Idempotent: safe to re-run. Re-running DROPs and recreates the tables, so it
-- also wipes the data — re-run the loader afterwards.
--
-- FIELD LISTS VERIFIED 2026-08-07 against BOTH the published data dictionaries
-- and the actual flat files (every single line counted, not a sample):
--
--   odi.cmpl  51 columns   2,232,666 rows   all lines exactly 51 fields
--   odi.rcl   29 columns     325,734 rows   all non-blank lines exactly 29 fields
--                                           (5 blank lines in the PRE_2010 part
--                                            are skipped by the loader)
--   odi.inv   11 columns     154,249 rows   all lines exactly 11 fields
--
-- !! The widely-circulated "complaints has 49 fields" figure is STALE. !!
-- NHTSA added field 50 (STATE_OF_INCIDENT) and field 51 (VEHICLE_OPERATOR) on
-- 30 April 2026. Likewise recalls is 29 fields, not 27: fields 28 (DO_NOT_DRIVE)
-- and 29 (PARK_OUTSIDE) were added in May 2025. If you are reading this long
-- after August 2026, re-check the dictionaries before the demo — load_nhtsa.py
-- will abort loudly if the file has drifted again.
-- ---------------------------------------------------------------------------

\set ON_ERROR_STOP on

CREATE SCHEMA IF NOT EXISTS odi;

COMMENT ON SCHEMA odi IS
  'NHTSA Office of Defects Investigation flat files, landed verbatim. '
  'Public domain. Physical column names are the publisher''s, unmodified.';


-- ===========================================================================
-- odi.cmpl — CONSUMER COMPLAINTS
-- Source: FLAT_CMPL.txt, dictionary https://static.nhtsa.gov/odi/ffdd/cmpl/CMPL.txt
-- 51 fields, TAB delimited, no header row.
-- Column order below MUST match the flat file field order exactly: the loader
-- COPYs positionally with no column list.
-- ===========================================================================
DROP TABLE IF EXISTS odi.cmpl CASCADE;

CREATE TABLE odi.cmpl (
    cmplid              TEXT,   --  1
    odino               TEXT,   --  2
    mfr_name            TEXT,   --  3
    maketxt             TEXT,   --  4
    modeltxt            TEXT,   --  5
    yeartxt             TEXT,   --  6
    crash               TEXT,   --  7
    faildate            TEXT,   --  8
    fire                TEXT,   --  9
    injured             TEXT,   -- 10
    deaths              TEXT,   -- 11
    compdesc            TEXT,   -- 12
    city                TEXT,   -- 13
    state               TEXT,   -- 14
    vin                 TEXT,   -- 15
    datea               TEXT,   -- 16
    ldate               TEXT,   -- 17
    miles               TEXT,   -- 18
    occurences          TEXT,   -- 19  [sic] publisher's misspelling, one 'r'. Kept.
    cdescr              TEXT,   -- 20  free-text complaint narrative
    cmpl_type           TEXT,   -- 21
    police_rpt_yn       TEXT,   -- 22
    purch_dt            TEXT,   -- 23
    orig_owner_yn       TEXT,   -- 24
    anti_brakes_yn      TEXT,   -- 25
    cruise_cont_yn      TEXT,   -- 26  NB: CRUISE_CONT_YN, *not* CRUISE_ACT_YN
    num_cyls            TEXT,   -- 27
    drive_train         TEXT,   -- 28
    fuel_sys            TEXT,   -- 29
    fuel_type           TEXT,   -- 30
    trans_type          TEXT,   -- 31
    veh_speed           TEXT,   -- 32
    dot                 TEXT,   -- 33
    tire_size           TEXT,   -- 34
    loc_of_tire         TEXT,   -- 35
    tire_fail_type      TEXT,   -- 36
    orig_equip_yn       TEXT,   -- 37
    manuf_dt            TEXT,   -- 38
    seat_type           TEXT,   -- 39
    restraint_type      TEXT,   -- 40
    dealer_name         TEXT,   -- 41
    dealer_tel          TEXT,   -- 42
    dealer_city         TEXT,   -- 43
    dealer_state        TEXT,   -- 44
    dealer_zip          TEXT,   -- 45
    prod_type           TEXT,   -- 46
    repaired_yn         TEXT,   -- 47
    medical_attn        TEXT,   -- 48
    vehicles_towed_yn   TEXT,   -- 49
    state_of_incident   TEXT,   -- 50  added 2026-04-30
    vehicle_operator    TEXT    -- 51  added 2026-04-30
);


-- ===========================================================================
-- odi.rcl — SAFETY RECALL CAMPAIGNS
-- Source: FLAT_RCL_PRE_2010.txt + FLAT_RCL_POST_2010.txt
--         dictionary https://static.nhtsa.gov/odi/ffdd/rcl/RCL.txt
-- 29 fields, TAB delimited, no header row.
-- VERIFIED 2026-08-07 against RCL.txt (Last Updated May 2025) *and* by counting
-- fields on all 325,739 lines of both flat files. No guessed columns here.
-- ===========================================================================
DROP TABLE IF EXISTS odi.rcl CASCADE;

CREATE TABLE odi.rcl (
    record_id           TEXT,   --  1
    campno              TEXT,   --  2
    maketxt             TEXT,   --  3
    modeltxt            TEXT,   --  4
    yeartxt             TEXT,   --  5
    mfgcampno           TEXT,   --  6
    compname            TEXT,   --  7
    mfgname             TEXT,   --  8
    bgman               TEXT,   --  9
    endman              TEXT,   -- 10
    rcltypecd           TEXT,   -- 11
    potaff              TEXT,   -- 12
    odate               TEXT,   -- 13
    influenced_by       TEXT,   -- 14
    mfgtxt              TEXT,   -- 15
    rcdate              TEXT,   -- 16
    datea               TEXT,   -- 17  same cryptic name as cmpl.datea, different meaning
    rpno                TEXT,   -- 18
    fmvss               TEXT,   -- 19
    desc_defect         TEXT,   -- 20
    conequence_defect   TEXT,   -- 21  [sic] publisher's misspelling of "consequence". Kept.
    corrective_action   TEXT,   -- 22
    notes               TEXT,   -- 23
    rcl_cmpt_id         TEXT,   -- 24
    mfr_comp_name       TEXT,   -- 25
    mfr_comp_desc       TEXT,   -- 26
    mfr_comp_ptno       TEXT,   -- 27
    do_not_drive        TEXT,   -- 28  added May 2025
    park_outside        TEXT    -- 29  added May 2025
);


-- ===========================================================================
-- odi.inv — DEFECT INVESTIGATIONS
-- Source: FLAT_INV.txt, dictionary https://static.nhtsa.gov/odi/ffdd/inv/INV.txt
-- 11 fields, TAB delimited, no header row.
-- VERIFIED 2026-08-07 against INV.txt (Last Updated September 5, 2023) and by
-- counting fields on all 154,249 lines.
--
-- NAMING NOTE: the dictionary calls field 1 "NHTSA ACTION NUMBER" — with spaces,
-- not an identifier. NHTSA publishes no canonical SQL column name for it. We use
-- nhtsa_action_number. This is OUR choice, the only one in this file; every other
-- column name is the publisher's verbatim. Flagged so nobody mistakes it for
-- source truth.
-- ===========================================================================
DROP TABLE IF EXISTS odi.inv CASCADE;

CREATE TABLE odi.inv (
    nhtsa_action_number TEXT,   --  1  see NAMING NOTE above
    make                TEXT,   --  2
    model               TEXT,   --  3
    year                TEXT,   --  4
    compname            TEXT,   --  5
    mfr_name            TEXT,   --  6
    odate               TEXT,   --  7
    cdate               TEXT,   --  8
    campno              TEXT,   --  9  joins to odi.rcl.campno
    subject             TEXT,   -- 10
    summary             TEXT    -- 11
);


-- ===========================================================================
-- Indexes
--
-- Sized for a live demo on a laptop: every scripted question must return in
-- well under a second, because dead air while an audience watches a spinner is
-- the fastest way to lose a room.
--
-- Built AFTER this script only in the sense that the loader runs next; Postgres
-- will populate them during COPY. If you are loading the full 2.2 M-row
-- complaints file and the load feels slow, drop the indexes, load, recreate.
-- For --subset 250000 the difference is not worth the extra step.
-- ===========================================================================

-- Complaints: the four columns every scripted question filters or groups on.
CREATE INDEX IF NOT EXISTS cmpl_maketxt_idx   ON odi.cmpl (maketxt);
CREATE INDEX IF NOT EXISTS cmpl_yeartxt_idx   ON odi.cmpl (yeartxt);
CREATE INDEX IF NOT EXISTS cmpl_compdesc_idx  ON odi.cmpl (compdesc);
CREATE INDEX IF NOT EXISTS cmpl_datea_idx     ON odi.cmpl USING btree (datea);

-- The two *other* date columns get an index too. The demo's central "which date
-- column did the model pick?" beat compares plans/results across all three, and
-- an unindexed faildate would make the wrong answer look slow rather than wrong.
CREATE INDEX IF NOT EXISTS cmpl_faildate_idx  ON odi.cmpl USING btree (faildate);
CREATE INDEX IF NOT EXISTS cmpl_ldate_idx     ON odi.cmpl USING btree (ldate);

-- Act 4 (hybrid search): full-text over the complaint narrative, combined with a
-- structured predicate on maketxt/yeartxt. Expression index with an explicit
-- regconfig — 'english' as a literal is IMMUTABLE, a bare to_tsvector(cdescr)
-- is not and would be rejected here.
-- coalesce() because cdescr is empty string / NULL on a small number of rows.
CREATE INDEX IF NOT EXISTS cmpl_cdescr_fts_idx
    ON odi.cmpl
    USING gin (to_tsvector('english', coalesce(cdescr, '')));

-- Recalls and investigations: enough to make joins and lookups instant.
CREATE INDEX IF NOT EXISTS rcl_maketxt_idx    ON odi.rcl (maketxt);
CREATE INDEX IF NOT EXISTS rcl_yeartxt_idx    ON odi.rcl (yeartxt);
CREATE INDEX IF NOT EXISTS rcl_compname_idx   ON odi.rcl (compname);
CREATE INDEX IF NOT EXISTS rcl_datea_idx      ON odi.rcl USING btree (datea);
CREATE INDEX IF NOT EXISTS rcl_campno_idx     ON odi.rcl (campno);

CREATE INDEX IF NOT EXISTS inv_make_idx       ON odi.inv (make);
CREATE INDEX IF NOT EXISTS inv_compname_idx   ON odi.inv (compname);
CREATE INDEX IF NOT EXISTS inv_campno_idx     ON odi.inv (campno);
CREATE INDEX IF NOT EXISTS inv_odate_idx      ON odi.inv USING btree (odate);


-- ===========================================================================
-- DELIBERATELY NOT CREATED: the friendly typed layer.
--
-- Below is the pattern a real project would apply on top of this landing schema.
-- It stays commented out on purpose. If these views existed, a model would read
-- `complaint_id`, `incident_date`, `date_added_to_file`, `occurrence_count` and
-- answer correctly with no semantic layer at all — which is precisely the
-- outcome this demo exists to disprove.
--
-- Uncomment ONLY in the "here is what good looks like" epilogue, if at all.
--
--   CREATE OR REPLACE VIEW odi.complaints_typed AS
--   SELECT
--       cmplid::bigint                                   AS complaint_id,
--       odino::bigint                                    AS odi_number,
--       mfr_name                                         AS manufacturer_name,
--       maketxt                                          AS make,
--       modeltxt                                         AS model,
--       NULLIF(yeartxt, '9999')::int                     AS model_year,
--       -- Three date columns, three different meanings. This mapping is the
--       -- entire knowledge the semantic layer is supposed to supply:
--       to_date(NULLIF(faildate, ''), 'YYYYMMDD')        AS incident_date,
--       to_date(NULLIF(ldate,    ''), 'YYYYMMDD')        AS received_by_nhtsa_date,
--       to_date(NULLIF(datea,    ''), 'YYYYMMDD')        AS added_to_file_date,
--       (crash  = 'Y')                                   AS crash_involved,
--       (fire   = 'Y')                                   AS fire_involved,
--       NULLIF(injured, '')::int                         AS persons_injured,
--       NULLIF(deaths,  '')::int                         AS fatalities,
--       compdesc                                         AS component_description,
--       NULLIF(occurences, '')::int                      AS occurrence_count,
--       cdescr                                           AS complaint_narrative
--   FROM odi.cmpl;
--
-- ===========================================================================


-- ===========================================================================
-- Verification
--
-- On a FIRST run (before the loader) every count is 0 and the date range is
-- NULL. That is expected — this script creates the tables, load_nhtsa.py fills
-- them. Re-run this SELECT after loading, or just read the loader's own summary.
--
-- The date range matters more than the row count. A previous version of this
-- demo asked the agent about a year that had no rows and returned an empty
-- result on stage. Always know your date range before you present.
-- ===========================================================================
SELECT
    'odi.cmpl' AS table_name,
    count(*)                                       AS row_count,
    min(NULLIF(datea, ''))                         AS min_datea,
    max(NULLIF(datea, ''))                         AS max_datea
FROM odi.cmpl
UNION ALL
SELECT
    'odi.rcl',
    count(*),
    min(NULLIF(datea, '')),
    max(NULLIF(datea, ''))
FROM odi.rcl
UNION ALL
SELECT
    'odi.inv',
    count(*),
    min(NULLIF(odate, '')),   -- inv has no datea; odate = date opened
    max(NULLIF(odate, ''))
FROM odi.inv;

-- Expected after a FULL load (measured against the files published 2026-08-07):
--   odi.cmpl  2232666   datea 19950103 .. 20260805
--   odi.rcl    325734   datea 19791012 .. 20260805  (PRE + POST 2010 parts)
--                       datea 20100104 .. 20260805  (POST 2010 part only)
--   odi.inv    154249   odate 19720310 .. 20260731  (inv has no datea column)
--
-- The complaints file grows daily, so your max_datea should be at or near
-- today's date. If it is not, you are loading a stale download.
