-- ==========================================================================
-- 02_comments.sql — GENERATED FILE. DO NOT HAND-EDIT.
-- ==========================================================================
--
-- Generated by : scripts/generate_comments.py
-- Generated on : 2026-09-02
-- Input dir    : /Users/bilge.ince/projects/vehicle-defect-semkb/data/raw
--
-- Source dictionaries (public domain, US DOT / NHTSA):
--   odi.cmpl   https://static.nhtsa.gov/odi/ffdd/cmpl/CMPL.txt
--   odi.rcl    https://static.nhtsa.gov/odi/ffdd/rcl/RCL.txt
--   odi.inv    https://static.nhtsa.gov/odi/ffdd/inv/INV.txt
--
-- Every description below is derived mechanically from the publisher's
-- own data dictionary. Nothing here was written by hand to make the
-- demo work. Where a field could not be parsed, the line reads
--     -- UNPARSED: <table>.<column>
-- rather than carrying an invented description.
--
-- Regenerate with:
--   python3 scripts/generate_comments.py > sql/02_comments.sql
-- ==========================================================================

\set ON_ERROR_STOP on

------------------------------------------------------------------------------
-- odi.cmpl
-- dictionary: CMPL.txt
-- source:     https://static.nhtsa.gov/odi/ffdd/cmpl/CMPL.txt
------------------------------------------------------------------------------
COMMENT ON TABLE odi.cmpl IS 'NHTSA Office of Defects Investigation consumer complaints. All safety-related defect complaints received by NHTSA since 1 January 1995. One row per complaint per component. Source: FLAT_CMPL.txt, tab delimited, public domain.';

COMMENT ON COLUMN odi.cmpl.cmplid IS 'NHTSA''s internal unique sequence number. Is an updateable field,thus data for a given record potentially could change from one data output file to the next. [CHAR(9)]';
COMMENT ON COLUMN odi.cmpl.odino IS 'NHTSA''s internal reference number. This number may be repeated for multiple components. Also, if LDATE is prior to Dec 15, 2002, this number may be repeated for multiple products owned by the same complainant. [CHAR(9)]';
COMMENT ON COLUMN odi.cmpl.mfr_name IS 'Manufacturer''s name [CHAR(40)]';
COMMENT ON COLUMN odi.cmpl.maketxt IS 'Vehicle/equipment make [CHAR(25)]';
COMMENT ON COLUMN odi.cmpl.modeltxt IS 'Vehicle/equipment model [CHAR(256)]';
COMMENT ON COLUMN odi.cmpl.yeartxt IS 'Model year, 9999 if unknown or N/A [CHAR(4)]';
COMMENT ON COLUMN odi.cmpl.crash IS 'Was vehicle involved in a crash, ''Y'' or ''N'' [CHAR(1)]';
COMMENT ON COLUMN odi.cmpl.faildate IS 'Date of incident (YYYYMMDD) [CHAR(8)]';
COMMENT ON COLUMN odi.cmpl.fire IS 'Was vehicle involved in a fire ''Y'' or ''N'' [CHAR(1)]';
COMMENT ON COLUMN odi.cmpl.injured IS 'Number of persons injured [NUMBER(2)]';
COMMENT ON COLUMN odi.cmpl.deaths IS 'Number of fatalities [NUMBER(2)]';
COMMENT ON COLUMN odi.cmpl.compdesc IS 'Specific component''s description [CHAR(128)]';
COMMENT ON COLUMN odi.cmpl.city IS 'Consumer''s city [CHAR(30)]';
COMMENT ON COLUMN odi.cmpl.state IS 'Consumer''s state code [CHAR(2)]';
COMMENT ON COLUMN odi.cmpl.vin IS 'Vehicle''s vin# [CHAR(11)]';
COMMENT ON COLUMN odi.cmpl.datea IS 'Date added to file (YYYYMMDD) [CHAR(8)]';
COMMENT ON COLUMN odi.cmpl.ldate IS 'Date complaint received by NHTSA (YYYYMMDD) [CHAR(8)]';
COMMENT ON COLUMN odi.cmpl.miles IS 'Vehicle mileage at failure [NUMBER(7)]';
COMMENT ON COLUMN odi.cmpl.occurences IS 'Number of occurrences [NUMBER(4)]';
COMMENT ON COLUMN odi.cmpl.cdescr IS 'Description of the complaint [CHAR(2048)]';
COMMENT ON COLUMN odi.cmpl.cmpl_type IS 'Source of complaint code: CAG = consumer action group; CON = forwarded from a congressional office; DP = defect petition,result of a defect petition; EVOQ = hotline VOQ; EWR = early warning reporting; INS = insurance company; IVOQ = NHTSA web site; LETR = consumer letter; MAVQ = NHTSA mobile app; MIVQ = NHTSA mobile app; MVOQ = optical marked VOQ; RC = recall complaint,result of a recall investigation; RP = recall petition,result of a recall petition; SVOQ = portable safety complaint form (PDF); VOQ = NHTSA vehicle owners questionnaire [CHAR(4)]';
COMMENT ON COLUMN odi.cmpl.police_rpt_yn IS 'Was incident reported to police ''Y'' or ''N'' [CHAR(1)]';
COMMENT ON COLUMN odi.cmpl.purch_dt IS 'Date purchased (YYYYMMDD) [CHAR(8)]';
COMMENT ON COLUMN odi.cmpl.orig_owner_yn IS 'Was original owner ''Y'' or ''N'' [CHAR(1)]';
COMMENT ON COLUMN odi.cmpl.anti_brakes_yn IS 'Anti-lock brakes ''Y'' or ''N'' [CHAR(1)]';
COMMENT ON COLUMN odi.cmpl.cruise_cont_yn IS 'Cruise control ''Y'' or ''N'' [CHAR(1)]';
COMMENT ON COLUMN odi.cmpl.num_cyls IS 'Number of cylinders [NUMBER(2)]';
COMMENT ON COLUMN odi.cmpl.drive_train IS 'Drive train type [AWD,4WD,FWD,RWD] [CHAR(4)]';
COMMENT ON COLUMN odi.cmpl.fuel_sys IS 'Fuel system code: FI = fuel injection; TB = turbo [CHAR(4)]';
COMMENT ON COLUMN odi.cmpl.fuel_type IS 'Fuel type code: BF = bifuel; CN = CNG/LPG; DS = diesel; GS = gas; HE = hybrid electric [CHAR(4)]';
COMMENT ON COLUMN odi.cmpl.trans_type IS 'Vehicle transmission type [AUTO, MAN] [CHAR(4)]';
COMMENT ON COLUMN odi.cmpl.veh_speed IS 'Vehicle speed [NUMBER(3)]';
COMMENT ON COLUMN odi.cmpl.dot IS 'Department of transportation tire identifier [CHAR(20)]';
COMMENT ON COLUMN odi.cmpl.tire_size IS 'Tire size [CHAR(30)]';
COMMENT ON COLUMN odi.cmpl.loc_of_tire IS 'Location of tire code: FSW = driver side front; DSR = driver side rear; FTR = passenger side front; PSR = passenger side rear; SPR = spare [CHAR(4)]';
COMMENT ON COLUMN odi.cmpl.tire_fail_type IS 'Type of tire failure code: BST = blister; BLW = blowout; TTL = crack; OFR = out of round; TSW = puncture; TTR = road hazard; TSP = tread separation [CHAR(4)]';
COMMENT ON COLUMN odi.cmpl.orig_equip_yn IS 'Was part original equipment ''Y'' or ''N'' [CHAR(1)]';
COMMENT ON COLUMN odi.cmpl.manuf_dt IS 'Date of manufacture (YYYYMMDD) [CHAR(8)]';
COMMENT ON COLUMN odi.cmpl.seat_type IS 'Type of child seat code: B = booster; C = convertible; I = infant; IN = integrated; TD = toddler [CHAR(4)]';
COMMENT ON COLUMN odi.cmpl.restraint_type IS 'Installation system code; A = vehicle safety belt; B = latch system [CHAR(4)]';
COMMENT ON COLUMN odi.cmpl.dealer_name IS 'Dealer''s name [CHAR(40)]';
COMMENT ON COLUMN odi.cmpl.dealer_tel IS 'Dealer''s telephone number [CHAR(20)]';
COMMENT ON COLUMN odi.cmpl.dealer_city IS 'Dealer''s city [CHAR(30)]';
COMMENT ON COLUMN odi.cmpl.dealer_state IS 'Dealer''s state code [CHAR(2)]';
COMMENT ON COLUMN odi.cmpl.dealer_zip IS 'Dealer''s zipcode [CHAR(10)]';
COMMENT ON COLUMN odi.cmpl.prod_type IS 'Product type code: V = vehicle; T = tires; E = equipment; C = child restraint [CHAR(4)]';
COMMENT ON COLUMN odi.cmpl.repaired_yn IS 'Was defective tire repaired ''Y'' or ''N'' [CHAR(1)]';
COMMENT ON COLUMN odi.cmpl.medical_attn IS 'Was medical attention required ''Y'' or ''N'' [CHAR(1)]';
COMMENT ON COLUMN odi.cmpl.vehicles_towed_yn IS 'Was vehicle towed ''Y'' or ''N'' [CHAR(1)]';
COMMENT ON COLUMN odi.cmpl.state_of_incident IS 'Incident state code [CHAR(2)]';
COMMENT ON COLUMN odi.cmpl.vehicle_operator IS 'Vehicle operator''s name [CHAR(40)]';

------------------------------------------------------------------------------
-- odi.rcl
-- dictionary: RCL.txt
-- source:     https://static.nhtsa.gov/odi/ffdd/rcl/RCL.txt
------------------------------------------------------------------------------
COMMENT ON TABLE odi.rcl IS 'NHTSA Office of Defects Investigation safety recall campaigns. All safety-related defect and compliance campaigns since 1967. Source: FLAT_RCL_PRE_2010.txt and FLAT_RCL_POST_2010.txt, tab delimited, public domain.';

COMMENT ON COLUMN odi.rcl.record_id IS 'Running Sequence Number, Which Uniquely Identifies The Record [NUMBER(9)]';
COMMENT ON COLUMN odi.rcl.campno IS 'NHTSA Recall Number [CHAR(12)]';
COMMENT ON COLUMN odi.rcl.maketxt IS 'Vehicle/Equipment Make [CHAR(25)]';
COMMENT ON COLUMN odi.rcl.modeltxt IS 'Vehicle/Equipment Model [CHAR(256)]';
COMMENT ON COLUMN odi.rcl.yeartxt IS 'Vehicle/Equipment Model Year, 9999 If Unknown Or N/A [CHAR(4)]';
COMMENT ON COLUMN odi.rcl.mfgcampno IS 'Manufacturer Campaign Number [CHAR(20)]';
COMMENT ON COLUMN odi.rcl.compname IS 'Component Description [CHAR(256)]';
COMMENT ON COLUMN odi.rcl.mfgname IS 'Manufacturer that filed Part 573 Defect/Noncompliance Report [CHAR(40)]';
COMMENT ON COLUMN odi.rcl.bgman IS 'Begin Date of Manufacturing [CHAR(8)]';
COMMENT ON COLUMN odi.rcl.endman IS 'End Date of Manufacturing [CHAR(8)]';
COMMENT ON COLUMN odi.rcl.rcltypecd IS 'Vehicle, Equipment, Child Restraint, Or Tire Part 573 Defect/Noncompliance Report [CHAR(4)]';
COMMENT ON COLUMN odi.rcl.potaff IS 'Potential Number of Units Affected [NUMBER(9)]';
COMMENT ON COLUMN odi.rcl.odate IS 'Date Manufacturer Notified Owners [CHAR(8)]';
COMMENT ON COLUMN odi.rcl.influenced_by IS 'Recall Initiated By (MFR/OVSC/ODI) [CHAR(36)]';
COMMENT ON COLUMN odi.rcl.mfgtxt IS 'Manufacturers of Recalled Vehicles/Equipment/Child Restraint/Tires [CHAR(40)]';
COMMENT ON COLUMN odi.rcl.rcdate IS 'Part 573 Defect/Noncompliance Report Received Date [CHAR(8)]';
COMMENT ON COLUMN odi.rcl.datea IS 'Record Creation Date [CHAR(8)]';
COMMENT ON COLUMN odi.rcl.rpno IS 'Regulation Part Number [CHAR(3)]';
COMMENT ON COLUMN odi.rcl.fmvss IS 'Federal Motor Vehicle Safety Standard Number [CHAR(3)]';
COMMENT ON COLUMN odi.rcl.desc_defect IS 'Defect Summary [CHAR(6000)]';
COMMENT ON COLUMN odi.rcl.conequence_defect IS 'Consequence Summary [CHAR(2000)]';
COMMENT ON COLUMN odi.rcl.corrective_action IS 'Corrective Summary [CHAR(6000)]';
COMMENT ON COLUMN odi.rcl.notes IS 'Recall Notes [CHAR(2000)]';
COMMENT ON COLUMN odi.rcl.rcl_cmpt_id IS 'Number That Uniquely Identifies A Recalled Component [CHAR(27)]';
COMMENT ON COLUMN odi.rcl.mfr_comp_name IS 'Manufacturer-Supplied Component Name [CHAR(50)]';
COMMENT ON COLUMN odi.rcl.mfr_comp_desc IS 'Manufacturer-Supplied Component Description [CHAR(200)]';
COMMENT ON COLUMN odi.rcl.mfr_comp_ptno IS 'Manufacturer-Supplied Component Part Number [CHAR(100)]';
COMMENT ON COLUMN odi.rcl.do_not_drive IS 'Consumer Advisory: Do Not Drive [CHAR(3)]';
COMMENT ON COLUMN odi.rcl.park_outside IS 'Consumer Advisory: Park Outside [CHAR(3)]';

------------------------------------------------------------------------------
-- odi.inv
-- dictionary: INV.txt
-- source:     https://static.nhtsa.gov/odi/ffdd/inv/INV.txt
------------------------------------------------------------------------------
COMMENT ON TABLE odi.inv IS 'NHTSA Office of Defects Investigation defect investigations. All safety-related defect investigations opened since 1972. CAMPNO, where present, identifies the recall campaign that resulted from the investigation and joins to odi.rcl.campno. Source: FLAT_INV.txt, tab delimited, public domain.';

COMMENT ON COLUMN odi.inv.nhtsa_action_number IS 'NHTSA Identification Number [CHAR(10)]';
COMMENT ON COLUMN odi.inv.make IS 'Vehicle/Equipment Make [CHAR(25)]';
COMMENT ON COLUMN odi.inv.model IS 'Vehicle/Equipment Model [CHAR(256)]';
COMMENT ON COLUMN odi.inv.year IS 'Model Year, 9999 if Unknown or N/A [CHAR(4)]';
COMMENT ON COLUMN odi.inv.compname IS 'Component Description [CHAR(256)]';
COMMENT ON COLUMN odi.inv.mfr_name IS 'Manufacturer''s Name [CHAR(40)]';
COMMENT ON COLUMN odi.inv.odate IS 'Date Opened (YYYYMMDD) [CHAR(8)]';
COMMENT ON COLUMN odi.inv.cdate IS 'Date Closed (YYYYMMDD) [CHAR(8)]';
COMMENT ON COLUMN odi.inv.campno IS 'Recall Campaign Number, if applicable [CHAR(9)]';
COMMENT ON COLUMN odi.inv.subject IS 'Summary Description [CHAR(200)]';
COMMENT ON COLUMN odi.inv.summary IS 'Summary Detail [CHAR(6000)]';

